name: Go

on:
  push:
    branches:
      - '*'
      - '**'
      - '!master'
  pull_request:
    branches:
      - '*'
      - '**'
      - '!master'

jobs:
  run_tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.14.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      run: go test -v ./...
